--FUNCIONES ESCALARES: DEVUELVEN UN SOLO VALOR

CREATE FUNCTION FN_CALCULADESCUENTO(@SUBTOTAL MONEY)
RETURNS MONEY
	BEGIN 
		RETURN @SUBTOTAL * 0.12
	END

SELECT DBO.FN_CALCULADESCUENTO(1500) AS DESCUENTO


SELECT F.NUM_FAC FACTURA,F.CAN_VEN*F.PRE_VEN SUBTOTAL
		,DBO.FN_CALCULADESCUENTO(F.PRE_VEN*F.CAN_VEN) AS DESCUENTO
FROM DETALLE_FACTURA F


--FUNCION QUE PERMITE MOSTRAR EL NOMBRE DEL DISTRITO A PARTIR DEL CODIGO DEL MISMO.
create function FN_MUESTRADISTRITO(@COD CHAR(3))
returns varchar(30)
begin 
	declare @dis varchar(30)
	select @dis = d.NOM_DIS 
	from DISTRITO d 
	where d.COD_DIS=@COD

	RETURN @dis
end


CREATE FUNCTION FN_MESLETRAS(@FECHA DATE)
RETURNS VARCHAR(20) 
AS
	BEGIN 
		DECLARE @NOMBRE VARCHAR(20)
		SET @NOMBRE =CAST(DATENAME(MONTH,@FECHA) AS VARCHAR)
		
		return @NOMBRE
	END


drop function FN_MESLETRAS

SELECT F.FEC_FAC AS NUMERO,
	F.FEC_FAC AS FECHA,
	CAST(DAY(F.FEC_FAC) AS CHAR(2))+' de '+DBO.FN_MESLETRAS(F.FEC_FAC)+ ' ' + CAST(YEAR(F.FEC_FAC) AS CHAR(4)) AS [FECHA EN LETRAS],
	F.EST_FAC ESTADO
FROM FACTURA F 



-------------FUNCIONES DE TABLA EN LINEA 


CREATE FUNCTION FN_PRODUCTOS()
RETURNS TABLE 
AS 
		RETURN(
				SELECT COD_PRO CODIGO , DES_PRO DESCRIPCION, PRE_PRO PRECIO,
						SAC_PRO [STOCK ACTUAL],SMI_PRO [STOCK MINIMO],UNI_PRO UNIDAD,
						LIN_PRO LINEA , IMP_PRO IMPORTADO
				FROM PRODUCTO 
				)
	
SELECT * FROM DBO.FN_PRODUCTOS()
drop function FN_PRODUCTOS	





CREATE FUNCTION FN_CLIENTEXDISTRITO(@NOMBRE VARCHAR(50))
RETURNS TABLE 
AS 
	RETURN(
		SELECT C.*
		FROM CLIENTE C 
		JOIN DISTRITO D ON C.COD_DIS=D.COD_DIS
		WHERE D.NOM_DIS =@NOMBRE
	)

SELECT *
FROM DBO.FN_CLIENTEXDISTRITO('SAN MIGUEL')



-------FUNCIONES TABLA MULTISENTENCIA 
CREATE FUNCTION FN_LISTADODISTRITO()
RETURNS @TABLA TABLE( COD CHAR(5),DIS VARCHAR(50) )
AS
	BEGIN 

		INSERT INTO @TABLA
			SELECT F.COD_DIS CODIGO,
				F.NOM_DIS DISTRITO
			FROM DISTRITO F
		RETURN
	END



CREATE FUNCTION FN_LISTADODISTRITO(@COD CHAR(3))
RETURNS @TABLA TABLE( COD CHAR(5),DIS VARCHAR(50) )
AS
	BEGIN 

		INSERT INTO @TABLA
			SELECT F.COD_DIS CODIGO,
				F.NOM_DIS DISTRITO
			FROM DISTRITO F
			WHERE F.COD_DIS =@COD
		
		RETURN
	END
DROP FUNCTION FN_LISTADODISTRITO

SELECT *
FROM DBO.FN_LISTADODISTRITO()



------EJERCICIOS 

--llamado a la funcion para que me muestre la deuda en una año determinado 
IF OBJECT_ID('fncDeudaContribuyente') IS NOT NULL
	DROP FUNCTION fncDeudaContribuyente

CREATE FUNCTION fncDeudaContribuyente(@CODIGO CHAR(11), @AÑO INT)
RETURNS DECIMAL(9,4)
AS
	BEGIN 
		DECLARE @DEUDA DECIMAL(9,4)

		SELECT @DEUDA = SUM(D.nGasto +D.nInteres+D.nReajuste+D.nTributo)
		FROM tDeudas D
		WHERE D.cCod_Cont =@CODIGO AND YEAR(D.cAño)=@AÑO
		GROUP BY D.cCod_Cont

		RETURN @DEUDA
	END

DROP FUNCTION fncDeudaContribuyente

SELECT DBO.fncDeudaContribuyente('0000132',2009)--128.1000


SELECT D.cCod_cont,SUM(D.nGasto +D.nInteres+D.nReajuste+D.nTributo)
		FROM tDeudas D
		WHERE YEAR(D.cAño)=2009 AND D.cCod_Cont ='0000132'
		GROUP BY D.cCod_Cont




---TAREA
--llamado a la funcion para que me muestre la deuda en una año todos
--pasarle parametro a la funcion 

CREATE FUNCTION fncDeudaContribuyenteAll(@CODIGO CHAR(11), @AÑO INT)
returns table 
as 
	return (
			SELECT D.cCod_Cont CODIGO,d.cAño AÑO , (D.nGasto +D.nInteres+D.nReajuste+D.nTributo) [TOTAL]
			FROM tDeudas D
			WHERE D.cCod_Cont =@CODIGO AND YEAR(D.cAño)=@AÑO
			
		)

DROP FUNCTION fncDeudaContribuyenteAll

SELECT *
FROM fncDeudaContribuyenteAll('0000132',2009)