--VISTAS

	--validación de la vista 
	IF OBJECT_ID('V_LISTAVENDEDOR') IS NOT NULL
		DROP VIEW V_LISTAVENDEDOR
	GO
	--creando vista
	CREATE VIEW V_LISTAVENDEDOR
	AS 
	SELECT V.COD_VEN AS CODIGO,
		   V.NOM_VEN +SPACE(1) +V.APE_VEN AS NOMBRE,
		   V.SUE_VEN AS SUELDO,
		   V.FIN_VEN AS [FECHA DE INICIO],
		   D.NOM_DIS AS DISTRITO
	FROM VENDEDOR V
	JOIN DISTRITO D ON D.COD_DIS=V.COD_DIS

	--resultado
	SELECT *
	FROM V_LISTAVENDEDOR

	--listar vendedores del distrito de la 'molina'
	select V.*
	FROM V_LISTAVENDEDOR V
	WHERE V.DISTRITO='LA MOLINA'

	--listar los vendedores cuyo año de inicio fue en los 90
	SELECT V.*
	FROM V_LISTAVENDEDOR V
	WHERE YEAR(V.[FECHA DE INICIO]) BETWEEN 1990 AND 1999

--CONTINUAMOS AQUI....

IF OBJECT_ID('V_DETALLEFACTURA') IS NOT NULL
DROP VIEW V_DETALLEFACTURA

CREATE VIEW V_DETALLEFACTURA
AS
	SELECT F.NUM_FAC AS 'NUMERO FACTURA',
	C.RSO_CLI AS NOMBRE,
	P.DES_PRO AS DESCRIPCION,
	D.CAN_VEN*D.PRE_VEN AS SUBTOTAL
FROM FACTURA F
JOIN CLIENTE C ON C.COD_CLI=F.COD_CLI
JOIN DETALLE_FACTURA D ON D.NUM_FAC= F.NUM_FAC
JOIN PRODUCTO P ON P.COD_PRO=D.COD_PRO

SELECT *
FROM CLIENTE

SELECT * FROM V_DETALLEFACTURA



IF OBJECT_ID('V_DETALLEFACTURA') IS NOT NULL
DROP VIEW V_DETALLEFACTURA

CREATE VIEW V_DETALLEFACTURA AS
SELECT F.NUM_FAC NUMERO,
C.RSO_CLI NOMBRE,
P.DES_PRO DESCRIPCION,
D.CAN_VEN*D.PRE_VEN SUBTOTAL

FROM FACTURA F 
JOIN CLIENTE C ON C.COD_CLI= F.COD_CLI
JOIN DETALLE_FACTURA D ON D.NUM_FAC=F.NUM_FAC
JOIN PRODUCTO P ON P.COD_PRO=D.COD_PRO

SELECT *
FROM V_DETALLEFACTURA





SELECT D.SUBTOTAL
FROM V_DETALLEFACTURA D
WHERE D.SUBTOTAL BETWEEN 30 AND 100--NO UTILIZA IGUALDAD ES MAS BIEN COMO DEFINIRLO QUE TE DE EN UN RANGO DE VALORES


SELECT D.*
FROM V_DETALLEFACTURA D 
WHERE D.NOMBRE='COREFO'




IF OBJECT_ID('V_MANTENIMIENTOPRODUCTO') IS NOT NULL
DROP VIEW V_MANTENIMIENTOPRODUCTO

--CREANDO VISTA 
CREATE VIEW V_MANTENIMIENTOPRODUCTO AS 
SELECT *
FROM PRODUCTO P


SELECT * FROM PRODUCTO

--INSERTANDO REGISTROS 
INSERT INTO V_MANTENIMIENTOPRODUCTO 
VALUES('P032','PORTALAPICEROS',5,100,10,'UNI',1,'V')

--ACTUALIZAR EL VALOR DE IMPORTADO A F OSEA FALSO

UPDATE V_MANTENIMIENTOPRODUCTO
SET COD_PRO='P032'
WHERE IMP_PRO='F'

